@startuml
    Vendeur.euse --> (Ajouter une commande)
    Vendeur.euse --> (supprimer une commande)
    Directeur --> (Voir rapport : les plus grands acheteurs)
    Directeur --> (Voir rapport : les articles plus vendus)
@enduml
