@startuml
    Vendeur.euse --> (Ajouter une commande)
    Vendeur.euse --> (Supprimer une commande)
    Directeur.trice --> (Voir rapport : les plus grands acheteurs)
    Directeur.trice --> (Voir rapport : les articles plus vendus)
@enduml
